# Site settings
email: icfaust@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Ian Faust
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Ian Faust 
profile_img: 
profile: 
social:
github: icfaust

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
