# Site settings
email: icfaust@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Ian Faust
description: Various projects related to Ian Faust's hobbies and work.
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Ian Faust 
profile_img: https://raw.githubusercontent.com/icfaust/icfaust.github.io/master/_screenshots/Ian_Faust.jpg
linkedin: Ian Faust
profile: Free from the bonds of grad school with an MIT PhD, he is now open to tinker and experiment.  His projects vary from the basic to the esoteric in coding, design and manufacturing. Currently living in Munich, he is exploring Europe and improving his German.
social:
github: icfaust
linkedin: https://www.linkedin.com/in/ian-faust-99b05519

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

plugins: ./_plugins
